### PR TITLE
Added option to enable code coverage

### LINKED ISSUE #16: Support enableCodeCoverage parameter
In our tests we are generating code coverage, but apparently xcodebuild ignores the setting in schema. Scan should look in the schema and add parameter `enableCodeCoverage` to build, if required. Otherwise at least another parameter should be added to scan to enable code coverage manually.

http://viteinfinite.com/2015/07/leveraging-swift-code-coverage-with-xcode-7/

### PR DESCRIPTION
**Pull request by Legoless**
This fixes #16. Please check if everything is okay.

### CODE REVIEW

**Comment by xfreebird** [comment]
@Legoless nice PR, but from code I can't see that being passed to xcodebuild anywhere, also what about retrieval of that data ? I understand we need the path to the derived data to compute the code coverage. Is there a different way besides adding xcargs "-derivedDataPath mypath" ?
It would be really cool if you could add that to this PR :). 

Anyways @KrauseFx is the one to decide.

**Comment by Legoless** [comment]
Code is being passed though test_command_generator. Derived data path could be also added as an option. @KrauseFx any thoughts?

**Comment by KrauseFx** [comment]
Interesting, this looks good @Legoless. Have you tested running it locally by running `./bin/scan` and see if the coverage reports appears inside Xcode?

**Comment by Legoless** [comment]
I'll test that, not sure yet. What this does is generate .profdata for the target in the derived data. @KrauseFx Do you mean to add ./bin/scan to a Run script phase? Code coverage is only displayed in Xcode once a build is run in Xcode, I believe. http://stackoverflow.com/questions/31096924/how-to-use-code-coverage-in-xcode-7

**Comment by fikeminkel** [comment]
Any progress on this PR? I was just about to submit my own PR for this issue when I saw this one :+1: 

Creating the profdata file makes it easy to integrate this in Jenkins with CodeCov so it would be really useful to have this merged.

**Comment by KrauseFx** [comment]
Oh, really sorry for the delay from my side, pushing a new release now :rocket: 
Thanks again @Legoless for your contribution.

**Comment by lemonkey** [comment]
Awesome :+1:

**Comment by lemonkey** [comment]
It will still be useful to be able to have finer grained control over scan such that you can leave out the workspace parameter and set a target instead when necessary.

**Pull request merged**
