### PR TITLE
Try loading the Scanfile from the current directory

### PR DESCRIPTION
**Pull request by alexcristea**
This pull request fixes a behaviour related to issue #42

### CODE REVIEW

**Comment by mfurtak** [comment]
@KrauseFx Is there anything we should be concerned about with regard to possibly loading two `Scanfile`s in one run? Is there any precedent for other tools to check multiple locations for the configuration?

**Comment by alexcristea** [comment]
@mfurtak, since I'm not very familiar with the ruby language, I was inspired by how `snapshot` is detecting configuration values: [snapshot/detect_values.rb ](https://github.com/fastlane/snapshot/blob/master/lib/snapshot/detect_values.rb)

**Comment by KrauseFx** [comment]
This should work, it's already the case in `snapshot`. Actually we should add this to all projects that require a project, meaning `gym` as well

**Comment by mfurtak** [comment]
@alexcristea @KrauseFx Excellent, thanks for that context :+1:

It would definitely be good to have a shared mechanism that automates the configuration search locations for consistency across all tools.

**Comment by mfurtak** [comment]
@alexcristea Thanks for the contribution :tada:

**Pull request merged**
